language: node_js
node_js:
  - 13

deploy:
  on:
    branch: master

services:
  - docker

before_script:
  - echo "Nothing to run here"

script:
  # Build the frontend ionic service
  - docker build -t udagram-frontend udagram-frontend/
  - docker tag udagram-frontend  matthausen/udagram-frontend:latest
  #- docker build -t udagram-api udagram-api/
  #- docker tag udagram-api matthausewn/udagram-api:latest

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push matthausen/udagram-frontend