language: node_js
node_js:
  - 13

deploy:
  on:
    branch: master

services:
  - docker

before_script:
  - echo "Nothing to run here"

script:
  # Build the nginx proxy server
  - docker build -t matthausen/udagram-proxy ./nginx
  # Build the user service api
  - docker build -t matthausen/udagram-api-user ./udagram-api/user
  # Build the feed service api
  - docker build -t matthausen/udagram-api-feed ./udagram-api/feed
  # Build the frontend ionic service
  - docker build -t matthausen/udagram-client ./udagram-frontend

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push matthausen/udagram-proxy
  - docker push matthausen/udagram-client
  - docker push matthausen/udagram-api-user
  - docker push matthausen/udagram-api-feed