apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api
  labels:
    app: udagram-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api
  template:
    metadata:
      labels:
        app: udagram-api
    spec:
      containers:
      - name: udagram-api
        image: matthausen/udagram-api
        ports:
        - containerPort: 80

