apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy-gateway
  name: reverseproxy-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy-gateway
  template:
    metadata:
      labels:
        service: reverseproxy-gateway
    spec:
      containers:
        - image: matthausen/udagram-micro-nginx:latest
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          name: reverseproxy-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-gateway-srv
spec:
  ports:
    - name: '8080'
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: reverseproxy-gateway
  type: LoadBalancer