apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api
  labels:
    app: udagram-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api
  template:
    metadata:
      labels:
        app: udagram-api
    spec:
      containers:
      - name: udagram-api
        image: matthausen/udagram-client
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8100

