apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: feed
          image: matthausen/udagram-api-feed:latest
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: AWS_REGION
              value: 'eu-west-1'
            - name: AWS_PROFILE
              value: 'default'
            - name: URL
              value: 'http://localhost:8100'

---
apiVersion: v1
kind: Service
metadata:
  name: feed-srv
spec:
  type: ClusterIP
  selector:
    app: feed
  ports:
    - name: feed
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: feed-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feed-depl
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50