apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-gateway-srv
spec:
  ports:
    - name: '8080'
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    service: reverseproxy-gateway
  type: LoadBalancer