apiVersion: v1
kind: Service
metadata:
  name: feed-srv
spec:
  type: ClusterIP
  selector:
    app: feed
  ports:
    - name: feed
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: feed-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feed-depl
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50